### ISSUE TITLE
Does not compile with newer conduit

### ISSUE THREAD

**Issue by mrkkrp** [snoyberg/bzlib-conduit#4]
The lib does not compile with `conduit-1.3.0`. The version bounds are incorrect.

Is the library still supported?

**Comment by snoyberg** [comment]
Yes, I just overlooked it. I'll release a new version with 1.3 support shortly.

**Comment by snoyberg** [comment]
bzlib-conduit 0.3.0 is released and is compatible with conduit 1.3.

**Comment by mrkkrp** [comment]
Any reason though that in `bzlib-conduit` operations are defined in terms of `MonadResource` while in `conduit-extra` you use the combo of `PrimMonad` and `MonadThrow`? For example I have the following code:

```haskell
decompressingPipe
  :: MonadResource m
  => CompressionMethod
  -> Conduit ByteString m ByteString
decompressingPipe Store   = C.awaitForever C.yield
decompressingPipe Deflate = Z.decompress $ Z.WindowBits (-15)
decompressingPipe BZip2   = BZ.bunzip2
```

Instead of converging to a single set of constraints, I have to have the whole bunch now: `(MonadResource, PrimMonad, MonadThrow)` together.

**Comment by snoyberg** [comment]
I can't say that I know for certain, since I didn't write this library, but
instead just took over maintainership. But a quick glance indicates that it
_is_ using ResourceT to ensure some resources are cleaned up in the case of
an exception.
